version: '3.9'

services:
  frontend:
    image: ghcr.io/noku-team/blockscout-frontend
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend-testchain'
    env_file:
      -  ../envs/common-frontend.env
    environment:
      - NEXT_PUBLIC_API_HOST=explorertest.3achain.org
