version: "3.9"

services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "../proxy:/etc/nginx/templates"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    labels:
      - traefik.enable=true
      - traefik.http.routers.blockscout-swiss-ledger-mainnet.rule=Host(`explorer.ledger.swiss`)
      - traefik.http.routers.blockscout-swiss-ledger-mainnet.entrypoints=web
      - traefik.http.services.blockscout-swiss-ledger-mainnet.loadbalancer.server.port=${BLOCKSCOUT_RETRIEVE_PORT}
    ports:
      - target: 80
        published: 4120
        protocol: tcp
        mode: host
      - target: 8080
        published: 8180
        protocol: tcp
        mode: host
      - target: 8081
        published: 8181
        protocol: tcp
        mode: host
    restart: always
    env_file:
      - ../envs/common-blockscout.env
    logging:
      options:
        max-size: 1g
